api generator / jwt 인증
bbakapple/monsing-server pull request #3
Opened 2024-11-25 09:41 UTC by kevstevie

인증로직 마지막 작업하게 api generator 보고 합쳐주세ㅐ요

2024-11-25 14:04 UTC, drunkenhw commented on api/src/main/kotlin/org/monsing/auth/AuthInterceptor.kt
> +            val header = request.getHeader("Authorization") ?: throw CredentialException("No Authorization header")
credential exception은 태어나서 처음보긴하는데 이거 던지면 어떤 처리하나요

2024-11-25 14:04 UTC, drunkenhw commented on api/src/main/kotlin/org/monsing/auth/TokenInterceptor.kt
> +        }
getPayload에서 예외를 던지는게 조금 더 깔끔해보이는데 어떤가요
굳이 검증을 하고 페이로드를 꺼내는 것보다 꺼낼 때 invalid token 이면 예외가 발생하는 건 어떠낙요

2024-11-25 14:04 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/jwt/TokenManager.kt
> +        .build()
companion object 로 만들면 좋겠네요

2024-11-25 14:04 UTC, drunkenhw commented on api/settings.gradle
> +rootProject.name = "openapi-spring"
ㄷㄷ settings.gradle은 제거해도 되지 않을까요 root project에 있으니

2024-11-25 14:04 UTC, drunkenhw commented on api/src/main/kotlin/org/monsing/auth/AuthConfig.kt
> +class AuthConfig(private val authInterceptor: AuthInterceptor) : WebMvcConfigurer {
```suggestion
class AuthConfig(
               private val authInterceptor: AuthInterceptor
) : WebMvcConfigurer {
```

2024-11-25 14:04 UTC, drunkenhw commented on api/.openapi-generator/FILES
> +src/main/kotlin/org/openapitools/SpringDocConfiguration.kt
얘는 머하는 파일인가요

2024-11-25 14:04 UTC, drunkenhw commented on api/.openapi-generator/VERSION
> +7.5.0
얘도 머하는 파일인가요

2024-11-26 04:20 UTC, kevstevie commented on api/src/main/kotlin/org/monsing/auth/AuthConfig.kt
> +class AuthConfig(private val authInterceptor: AuthInterceptor) : WebMvcConfigurer {
오 감사합니다

2024-11-26 04:20 UTC, kevstevie commented on api/src/main/kotlin/org/monsing/auth/AuthInterceptor.kt
> +            val header = request.getHeader("Authorization") ?: throw CredentialException("No Authorization header")
오 이름 그럴싸한거로 해두고 바꾸려고 했는데 까먹엇네요

2024-11-26 04:20 UTC, kevstevie commented on app/src/main/kotlin/org/monsing/jwt/TokenManager.kt
> +        .build()
오 근데 키가 컴패니언이 아니라 parser를 컴패니언으로 만들 수가 없어요 
value에서 주입하는 걸 컴패니언으로 만들 수 잇나요

2024-11-26 04:20 UTC, kevstevie commented on api/src/main/kotlin/org/monsing/auth/TokenInterceptor.kt
> +        }
token manager에서 에외 던지도록 수정햇읍니다
IAE는 400으로 처리하고 expired jwt token 다시 던져서 예외핸들러에서 처리하게 하는건 어떤가요
바꾼거 확인해주세요

2024-11-26 04:54 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/jwt/TokenManager.kt
> +        .build()
ㄲㅂ

2024-11-26 04:57 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/jwt/TokenPayload.kt
> +data class TokenPayload(val id: Long)
오 value class 한번 써보는 것도 좋을 것 같네요 (한번도 안써봄)

2024-11-26 04:57 UTC, drunkenhw approved these changes

2024-11-26 04:57 UTC, carsago commented
고생하셨습니다.

2024-11-26 04:59 UTC, carsago approved these changes

2024-11-26 04:59 UTC, carsago commented on app/src/main/kotlin/org/monsing/jwt/TokenPayload.kt
> +data class TokenPayload(val id: Long)
오타쿠 말투 같네요.

2024-11-26 04:59 UTC, carsago commented on api/build.gradle
> +        inputSpec.set("$contractDir/${yamlFile.name}")
```suggestion
sout('hello world')
```

suggestion 안한지 오래된 거 같아서 해봤습니다!!

2024-11-26 05:12 UTC, kevstevie commented on app/src/main/kotlin/org/monsing/jwt/TokenPayload.kt
> +data class TokenPayload(val id: Long)
오 근데 value class는 원시값 래핑에 쓰는거 같아서 role같은 추가 payload가 생길수잇으니 놔두겟습니다

2024-11-26 06:06 UTC, Jaeyoung22 requested changes
고생하셨습니다

2024-11-26 06:06 UTC, Jaeyoung22 commented on api/.openapi-generator/FILES
> +src/main/kotlin/org/openapitools/SpringDocConfiguration.kt
파일 빼주세요

2024-11-26 06:06 UTC, Jaeyoung22 commented on api/.openapi-generator/VERSION
> +7.5.0
파일 빼주세요

2024-11-26 06:06 UTC, Jaeyoung22 commented on api/settings.gradle
> +rootProject.name = "openapi-spring"
이거 api generator가 자동으로 생성한건데 혹시 모르니까 두죠

2024-11-26 06:06 UTC, Jaeyoung22 commented on app/src/main/resources/application.yml
> +  access-key: akdsmksamdkdamkdkmasdkmdakm
서브 모듈 설정 나중에 부탁합니다

2024-11-26 06:06 UTC, Jaeyoung22 commented on domain/src/main/kotlin/org/monsing/report/ReportRepository.kt
> +interface ReportRepository : JpaRepository<Report, Long>
@drunkenhw 오해할까봐 얘기하는데 코드 정리는 제가 했습니다. 성민이가 했다고 오해하지 마세요

2024-11-26 06:08 UTC, drunkenhw commented on api/settings.gradle
> +rootProject.name = "openapi-spring"
이거 없어도 정상동작하는거 확인했습니다. 지우는게 좋을 것 같아요

2024-11-26 06:08 UTC, kevstevie commented on domain/src/main/kotlin/org/monsing/report/ReportRepository.kt
> +interface ReportRepository : JpaRepository<Report, Long>
ㅋㅋ

2024-11-26 06:09 UTC, kevstevie commented on app/src/main/resources/application.yml
> +  access-key: akdsmksamdkdamkdkmasdkmdakm
확인햇습니다

2024-11-26 06:10 UTC, Jaeyoung22 requested changes

2024-11-26 06:10 UTC, Jaeyoung22 commented on api/settings.gradle
> +rootProject.name = "openapi-spring"
그럼 지워주세요

2024-11-26 06:11 UTC, Jaeyoung22 approved these changes

2024-11-26 06:11 UTC, merged