refresh token / login / register 구현
bbakapple/monsing-server pull request #4
Opened 2024-11-26 09:28 UTC by kevstevie

oauth api 사용 미구현

구현되어 있는거 구조만 한번 봐주십쇼
테스트 어케 짤지도 좀 알려주세요

2024-11-26 10:59 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/AuthService.kt
> +        )
response, request는 뭔가 api 모듈에 잇어야할 것 같은 느낌이라 생각하는데, 그래서 application 모듈에서는 domain을 반환하는게 어떨까 생각

2024-11-26 10:59 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/AuthService.kt
> +        val id = member.id ?: throw IllegalStateException("Member id must not be null")
```suggestion
        val id = requireNotNull(member.id){
        "Member id must not be null"
        }
```

2024-11-26 10:59 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/OauthAdaptor.kt
> +    }
companion object의 컨벤션은 보통 맨 아래입니다.
그리고 companion object 도 좋은 것 같은데 각 벤더사의 handler 를 bean으로 등록해서 자동으로 등록되게 하는게 실수 없고 좋을 것 같다는 생각입니다.
각 핸들러는 어떤 Provider type을 처리할 수 있는지 정의하고.

2024-11-26 10:59 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/oauthhandler/GoogleOauthHandler.kt
> +private const val GOOGLE_OAUTH_URL = "https://www.googleapis.com/oauth2/v2/userinfo"
얘는 왜 companion object가 아니라 밖에 나와있나요?

2024-11-26 10:59 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/oauthhandler/GoogleOauthHandler.kt
> +    }
spring의 HTTP interface 사용하면 좀 더 깔끔해지지 않을까라는 생각입니다

2024-11-26 10:59 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/jwt/TokenManager.kt
> +    @Value("\${jwt.refresh-token.secret}") refreshSecret: String,
secret은 왜 private 이 아닌가요?

2024-11-26 10:59 UTC, drunkenhw commented on domain/src/main/kotlin/org/monsing/member/Member.kt
> +import jakarta.persistence.*
다시 합체

2024-11-26 14:46 UTC, Jaeyoung22 requested changes

2024-11-26 14:46 UTC, Jaeyoung22 commented on app/src/main/kotlin/org/monsing/auth/AuthService.kt
> +        )
이거 openapi generator 사용하면 api 모듈에 있게 돼서 우석이 말대로 domain 반환하던지 아니면 dto로 한번 더 감싸는 형태도 좋아요

2024-11-26 14:46 UTC, Jaeyoung22 commented on app/src/main/kotlin/org/monsing/auth/RegisterRequest.kt
> +)
얘네는 api 모듈에 자동으로 등록되도록 해놓겠습니다

2024-11-26 14:46 UTC, Jaeyoung22 commented on app/src/main/kotlin/org/monsing/auth/oauthhandler/GoogleOauthHandler.kt
> +private const val GOOGLE_OAUTH_URL = "https://www.googleapis.com/oauth2/v2/userinfo"
클래스 바깥에서 선언도 되네?

2024-11-26 14:46 UTC, Jaeyoung22 commented on app/src/main/kotlin/org/monsing/auth/oauthhandler/GoogleOauthHandler.kt
> +private const val GOOGLE_OAUTH_URL = "https://www.googleapis.com/oauth2/v2/userinfo"
코틀린 개신기하네 생성자까지만 읽었는데 더 읽어야겠네

2024-11-26 14:46 UTC, Jaeyoung22 commented on domain/src/main/kotlin/org/monsing/member/Member.kt
> +import jakarta.persistence.*
이거 인테리제이에서 깔으라고 하는 코틀린 플러그인 적용하면

그 코드 스타일에서 와일드카드 없게 해놔도 저 플러그인에 있는 스타일이 먼저 적용돼서 안됨

마지막쪽 탭인가에 있는 그 플러그인 삭제하셈

2024-11-27 10:24 UTC, kevstevie commented on app/src/main/kotlin/org/monsing/auth/AuthService.kt
> +        val id = member.id ?: throw IllegalStateException("Member id must not be null")
좋습니다

2024-11-27 10:24 UTC, kevstevie commented on app/src/main/kotlin/org/monsing/auth/AuthService.kt
> +        )
오 근데 token response는 어떻게 해야될지 잘 모르겟어요
도메인도 아니고 무엇도 아닌 느낌

2024-11-27 10:24 UTC, kevstevie commented on app/src/main/kotlin/org/monsing/auth/OauthAdaptor.kt
> +    }
좋습니다

2024-11-27 10:24 UTC, kevstevie commented on app/src/main/kotlin/org/monsing/auth/RegisterRequest.kt
> +)
좋습니다

2024-11-27 10:24 UTC, kevstevie commented on app/src/main/kotlin/org/monsing/auth/oauthhandler/GoogleOauthHandler.kt
> +    }
아름답네요

2024-11-27 10:24 UTC, kevstevie commented on app/src/main/kotlin/org/monsing/jwt/TokenManager.kt
> +    @Value("\${jwt.refresh-token.secret}") refreshSecret: String,
field가 아니라서 그렇습니다

2024-11-27 10:24 UTC, kevstevie commented on domain/src/main/kotlin/org/monsing/member/Member.kt
> +import jakarta.persistence.*
오 좋습니다

2024-11-27 10:25 UTC, kevstevie commented on app/src/main/kotlin/org/monsing/auth/oauth/OauthAdaptor.kt
> +}
오 근데 이렇게 해도 되나요

2024-11-28 05:24 UTC, drunkenhw approved these changes

2024-11-28 05:24 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/AuthService.kt
> +        )
token도 저희 서비스에 중요한 역할을 하니 vo로 볼 수 있지 않을까요?
Token이라는 vo를 만들고 vo를 던지면 좋을 것 같다는 생각입니다.

2024-11-28 05:24 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/AuthService.kt
> +        val id = member.id ?: throw IllegalStateException("Member id must not be null")
여기도 requireNotNull

2024-11-28 05:24 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/TokenResponse.kt
> +data class TokenResponse(
얘를 vo로...

2024-11-28 05:24 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/apiclient/OauthApiClientConfig.kt
> +            .baseUrl("https://www.googleapis.com/oauth2/v2/userinfo")
base url에 https://www.googleapis.com 까지만하고
@GetExchange("/oauth2/v2/userinfo") 이런식으로 하는게 좀 더 유연할듯?

2024-11-28 05:24 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/apiclient/OauthApiClientConfig.kt
> +            .baseUrl("https://www.googleapis.com/oauth2/v2/userinfo")
근데 구글에 찌르는 api 토큰은 원래 없나요? 무한으로 찌를 수 있는건가...?

2024-11-28 05:24 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/jwt/TokenManager.kt
> +        val expiration = issuedAt.toInstant().plusSeconds(refreshExpireSecond).let { Date.from(it) }
별건 아니지만 깔끔하게 메서드로 분리하는 것도 좋을 것 같습니다

2024-11-28 05:24 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/jwt/TokenManager.kt
> +        val expiration = issuedAt.toInstant().plusSeconds(refreshExpireSecond).let { Date.from(it) }
위에도 반복하고 있어보여서

2024-11-28 07:02 UTC, Jaeyoung22 commented on app/src/main/kotlin/org/monsing/auth/apiclient/OauthApiClientConfig.kt
> +            .baseUrl("https://www.googleapis.com/oauth2/v2/userinfo")
api 토큰이 무슨 말인가요?

2024-11-28 07:04 UTC, Jaeyoung22 approved these changes

2024-11-28 07:06 UTC, Jaeyoung22 commented on app/src/main/kotlin/org/monsing/auth/apiclient/OauthApiClientConfig.kt
> +            .baseUrl("https://www.googleapis.com/oauth2/v2/userinfo")
그 저기 ApiClient랑 handle이 파라미터로 가지고 잇는 토큰이랑 다른건가용?

2024-11-28 13:39 UTC, drunkenhw commented on app/src/main/kotlin/org/monsing/auth/apiclient/OauthApiClientConfig.kt
> +            .baseUrl("https://www.googleapis.com/oauth2/v2/userinfo")
구글에서 발급받은 secret? 같은게 없는가 해서요

2024-11-28 15:48 UTC, kevstevie commented on app/src/main/kotlin/org/monsing/auth/apiclient/OauthApiClientConfig.kt
> +            .baseUrl("https://www.googleapis.com/oauth2/v2/userinfo")
재활용 가능성이 별로없어보이는데 일단 나누긴햇습니다.
그러게요 토큰 받을때만 필요한가 정우한테 한번 물어보죠

2024-11-29 00:15 UTC, merged